### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by oobles** [snazy/ohc#35]
We are using the linked implementation of the off heap cache.  After running for multiple hours we think we are seeing some fragmentation issues with more memory being used than expected.

The following suggests using jemalloc.  We have tried setting the environment variable to LD_PRELOAD=/usr/lib64/libjemalloc.so.1 to preload the allocation library.  

| Since this implementation performs alloc/free operations for each individual entry, take care of 
| memory fragmentation. We recommend using jemalloc to keep fragmentation low. On Unix 
| operating systems, preload jemalloc. OSX usually does not require jemalloc for performance 
| reasons.

Is there any way to verify that ohc is using jemalloc?

Also, how is it possible to "take care of memory fragmentation" other than using jemalloc?  Will jemalloc completely fix fragmentation issues?

| The extension jar ohc-core-j8 is not recommmended for the linked implementation to use of new 
| sun.misc.Unsafe methods in Java 8 exists.

I'm having trouble understanding the above sentence.  Are you saying do not use ohc-core-j8 on java 8 with Linked implementaiton?

**Comment by snazy** [comment]
Well, you cannot do more from the environment side than using jemalloc IMO. With _take care_ and the sentence before, I had in mind that since memory is allocated for each individual entry, memory fragmentation can occur - especially if the size of the entries is not uniform - but should level out after a while. Means, it is a good idea to leave some head room.

Also note, that especially the linked implementation can allocate *more* memory than defined, while operations like _put_ are in-flight (i.e. not counted towards a segment). This is a performance optimization to not lock the segment more often than absolutely necessary.

Using `export LD_PRELOAD=/usr/lib64/libjemalloc.so.1` should be fine. The mechanism "routes" `malloc` and `free` calls from the application to jemalloc. I.e. also the JVM will use jemalloc. The chapter in the doc has been updated.

The ohc-core-j8 sentence is wrong - I've fixed it. It should say, that it *is* recommended.
